apiVersion: v2
name: k8s-helm-templates
description: Helm chart genérico para aplicações Java Bootstrap e microserviços K8s
type: application

version: 0.0.1

appVersion: "0.0.1"

home: https://github.com/rg-hermann/k8s-helm-templates
