{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-helm-templates.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "k8s-helm-templates.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-helm-templates.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml (.Values.networkPolicy.policyTypes | default (list "Ingress" "Egress")) | nindent 4 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
