{{- if or .Values.secrets .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-helm-templates.fullname" . }}
  labels:
    {{- include "k8s-helm-templates.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.secret.stringData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}