apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-generic.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-generic.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-generic.name" . }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ include "app-generic.fullname" . }}-configmap
            {{- end }}
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "app-generic.fullname" . }}-secret
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "app-generic.fullname" . }}-pvc
        {{- end }}
